services:
  paperless-ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    network_mode: bridge
    volumes:
      - paperless-ai_data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  paperless-ai_data: